W-16431086: Document changes around compilation of connectors with Java 17
mulesoft/docs-mule-sdk pull request #270
Opened 2024-11-14 13:13 UTC by elrodro83

Ref: https://docs.google.com/document/d/1fGOmV5qkiuqqQZe6iN09z_3gxKVeIHdLOTFnaaISlb0/edit?tab=t.0

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2025-01-10 13:50 UTC, marianogonzalez requested changes

2025-01-10 13:50 UTC, marianogonzalez commented on modules/ROOT/pages/general-coding-rules.adoc
> +=== Java Compatibility
why remove this but keep the Java 11 compatibility section below?

2025-01-10 13:50 UTC, marianogonzalez commented on modules/ROOT/pages/getting-started.adoc
> +  <version>1.9.0</version>
this section needs to explain (or refer to) that for connectors to be used in 4.4 or 4.6 parent poms 1.4.x or 1.6.x need to be used. Need to keep that until 4.6 goes EOL

2025-01-10 13:50 UTC, marianogonzalez commented on modules/ROOT/pages/java-version-support.adoc
> +   <version>0.10.1</version>
won't 0.11 be the latest by the time of release?

2025-01-10 13:50 UTC, marianogonzalez commented on modules/ROOT/pages/java-version-support.adoc
> +[[bytecode_level]]
same as with the other PR. Customers should not meddle with this. Use parent pom versions exclusively

2025-01-10 17:24 UTC, sathya0 commented on modules/ROOT/pages/getting-started.adoc
> +  <version>1.9.0</version>
what about 4.5?

2025-01-13 14:14 UTC, marianogonzalez requested changes

2025-01-13 14:14 UTC, marianogonzalez commented on modules/ROOT/pages/certification-guidelines-for-connectors.adoc
> +  <version>1.9.0</version>
This is incorrect. Please revert

2025-01-13 14:14 UTC, marianogonzalez commented on modules/ROOT/pages/getting-started.adoc
> +  <version>1.9.0</version>
4.5 is EOL

2025-01-13 14:14 UTC, marianogonzalez commented on modules/ROOT/pages/getting-started.adoc
> +NOTE: Connectors used in Mule 4.4.x and Mule 4.6.x must use parent POM 1.4.x and 1.6.x respectively.
This line is incorrect/misleading. What the parent pom defines is the minMuleVersion. That MMV needs to be compatible with whatever the target mule version will be, but there's no need to make then match expicitly. There's also no fundamental change with the currently documented behavior other than using 1.9.0 when Java 17 bytecode is needed

2025-01-13 14:14 UTC, marianogonzalez commented on modules/ROOT/pages/java-version-support.adoc
> +. Ensure the bytecode level of the compiled classes of your custom module can be used in the lowest supported Java version. Use the Java compiler configuration from the Java SDK parent POM instead of
delete lines 43 to 59

2025-01-13 14:14 UTC, marianogonzalez commented on modules/ROOT/pages/testing-writing-your-first-test-case.adoc
> +<version>1.9.0</version>
This is incorrect. This would only work for Java 17 compiled connectors and would break all others. In any case, we must direct users towards MTF or else we'll have the same migration issue again when we adopt Java 21. 

The java testing framework should be shown as deprecated and for legacy connectors only

2025-01-15 17:40 UTC, sathya0 commented on modules/ROOT/pages/certification-guidelines-for-connectors.adoc
> +  <version>1.9.0</version>
Should i revert to 1.0.0?

2025-01-15 17:52 UTC, sathya0 commented on modules/ROOT/pages/testing-writing-your-first-test-case.adoc
> +<version>1.9.0</version>
MTF is not publicly available, these docs are for all customers

2025-01-15 21:07 UTC, marianogonzalez requested changes

2025-01-15 21:07 UTC, marianogonzalez commented on modules/ROOT/pages/getting-started.adoc
> +NOTE: The parent POM defines the minimum Mule version, which must be compatible with the target Mule version.
This is not sufficient to address the original comment. This is the getting started page. At this point, the reader has no context to understand what any of this means. They also have no way of knowing which parent pom version corresponds to which mule version nor the supported byte code level

2025-01-20 17:50 UTC, marianogonzalez submitted a review, later dismissed

2025-01-30 20:48 UTC, Crispy-Salesforce approved these changes

2025-01-31 17:28 UTC, merged