Update special-parameters.adoc
mulesoft/docs-mule-sdk pull request #72
Opened 2020-08-19 20:46 UTC by giordanolucas

2020-08-25 21:37 UTC, sarathecoubian commented on modules/ROOT/pages/special-parameters.adoc
>  WARNING: Expression resolution is deferred until it is required, so `resolve()` can fail due to an invalid expression.
```suggestion
[WARNING]
====
* Expression resolution is deferred until it is required, so `resolve()` can fail due to an invalid expression.
* Parameter resolvers are allowed only in operations. As such, you cannot use parameter resolvers in configurations.
```

2020-08-25 21:38 UTC, sarathecoubian commented on modules/ROOT/pages/special-parameters.adoc
> +WARNING: Parameter Resolvers are only allowed in Operations. Dont try to use these in Configurations.
```suggestion
```

2020-08-25 21:38 UTC, sarathecoubian requested changes
Warning block. If these should not be grouped together, please let me know.

2020-08-26 16:48 UTC, giordanolucas commented
@sarathecoubian Just added the suggested changes

2020-08-27 14:43 UTC, sarathecoubian approved these changes

2020-08-27 14:43 UTC, merged